### ISSUE TITLE
This package breaks the project

### ISSUE THREAD

**Issue by magyarb** [dansmaculotte/nuxt-segment#4]
After adding this package, the nuxt server stops working. Here's the error with the stack trace: 

```
FATAL  The 'request' argument must be string. Received type undefined

  at node_modules\esm\esm.js:1:224803
  at Module.<anonymous> (node_modules\esm\esm.js:1:295892)
  at Resolver.n [as esm] (node_modules\esm\esm.js:1:279589)
  at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:569:31)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:164:36)
  at promise.then (node_modules\@nuxt\utils\dist\utils.js:1802:43)
```

I'm using nuxt 2.11.0. This might be an issue with webpack configuration, but the solution is missing from the docs.

**Comment by gaelreyrol** [comment]
Hello @magyarb ! Could you provide more context ? Options for example ?

**Comment by magyarb** [comment]
I used the default 

```
{
    writeKey: '',
    disabled: false,
    useRouter: true
  }
```

As esm is the package that throws the error, this was likely a problem with transpilation not configured properly. 

Anyway, creating `segment.js` in `plugins` with the content

```
export default () => {
 //the code segment provided
}
```
and including in `nuxt.config.js` like:

`plugins: [{src: '~/plugins/segment', mode: 'client'}]`

works perfectly well. What additional value does this package provide over this solution?

**Comment by gaelreyrol** [comment]
Thanks @magyarb ! I will try to work on this ASAP !
